support coloration schemes on non-chrome browsers
fcomb/redux-logger pull request #203
Opened 2017-02-18 18:48 UTC by wegry

This has been tested on Chrome 56, Firefox 51, and Safari 10. I don't have access to a machine running Edge or IE, but this should also disable coloration and the formatting tokens by default for them.

2017-07-03 15:11 UTC, wallacyyy commented
Is someone looking into this ? Is a nice feature, nowadays the color formatting does not look good on Firefox.

2017-07-03 18:56 UTC, wegry commented
This looks to be dead on arrival. I cut the PR before the transition between redux-logger@2.* and 3.

> On Jul 3, 2017, at 11:11 AM, Leonardo Couto <notifications@github.com> wrote:
> 
> Is someone looking into this ? Is a nice feature, nowadays the color formatting does not look good on Firefox.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/evgenyrodionov/redux-logger/pull/203#issuecomment-312671762>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AE6wCa5zdGaiz6pBIahouPd27e51c39Rks5sKQSRgaJpZM4MFNgi>.
>

2017-07-03 19:27 UTC, wegry commented
Resending to rest of the list.

This looks to be dead on arrival. I cut the PR before the transition between redux-logger 2 and 3.

> On Jul 3, 2017, at 11:11 AM, Leonardo Couto <notifications@github.com> wrote:
> 
> Is someone looking into this ? Is a nice feature, nowadays the color formatting does not look good on Firefox.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/evgenyrodionov/redux-logger/pull/203#issuecomment-312671762>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AE6wCa5zdGaiz6pBIahouPd27e51c39Rks5sKQSRgaJpZM4MFNgi>.
>

2017-08-16 14:06 UTC, imevro requested changes
Can you update please? It looks very promising, I want to merge it.

2017-09-08 01:36 UTC, pelotom commented
Would this PR support colors in node (i.e. when testing with Mocha or Jest)?

2021-12-08 17:09 UTC, closed without merging